MILLENNIUMDB_DIR=`pwd`/mdb/scratch
MILLENNIUMDB_GRAPH=${MILLENNIUMDB_DIR}/graph-data
MILLENNIUMDB_OUTPUT=${MILLENNIUMDB_DIR}/output
MILLENNIUMDB_QUERIES=`pwd`/mdb/queries
MILLENNIUMDB_BINARIES=`pwd`/mdb/millenniumdb-binaries
MILLENNIUMDB_LOAD_SCRIPT=`pwd`/mdb/convert_csv.sh
RESULTS_FILE=`pwd`/results/results.csv

# Set to 1 for using cache, 0 for no cache.
MILLENNIUMDB_CACHE=1
MILLENNIUMDB_CACHE_DIR=${MILLENNIUMDB_DIR}/cache
MILLENNIUMDB_GRAPH_SOURCE_FILE=${MILLENNIUMDB_CACHE_DIR}/graph-sf${SF}.txt
MILLENNIUMDB_CHECKSUMS=${MILLENNIUMDB_CACHE_DIR}/checksums

MILLENNIUMDB_PORT=48785
# default: 1GiB = 262144 * 4KiB
# 8GiB = 2097152 * 4KiB
MILLENNIUMDB_BUFFER_SIZE=2097152
# default: 64MiB = 16384 * 4KiB
# 512MiB = 1048576 * 4KiB
MILLENNIUMDB_PRIVATE_BUFFER_SIZE=131072
# 1 minutes
MILLENNIUMDB_TIMEOUT=60

MILLENNIUMDB_CONTAINER=lsqb-mdb

MILLENNIUMDB_REQUIRES_BUILD=$([ -f ${MILLENNIUMDB_BINARIES}/create_db ] && \
        [ -f ${MILLENNIUMDB_BINARIES}/server ] && \
        [ -f ${MILLENNIUMDB_BINARIES}/query ] && echo "false" || echo "true")
